common:
  fp16: true
  disable_tqdm: true # set true when using nohup
  seed: 0

path:
  checkpoint: "models/hubert/checkpoint_sid"

dataset:
  root: "data/VoxCeleb1"
  download: false
  max_sample_size: 128000

dataloader:
  batch_size: 100 # work with single 24GB VRAM GPU
  num_workers: 30

model:
  model_type: "hubert"
  model_name_or_path: "facebook/hubert-base-ls960"
  classifier_proj_size: 256
  num_labels: 1251 # VoxCeleb1
  segmentation_layer: 8

optim:
  epoch: 50
  lr: 0.001
  weight_decay: 0.01